### ISSUE TITLE
当为图片添加说明时，会导致图片无法自动适应屏幕显示

### ISSUE THREAD

**Issue by hiikii** [Vtrois/Dobby#11]
**问题描述**

我尝试给一张尺寸大概在 1024×500 左右的图片添加说明时，发现网页呈现出的图片会超出文章内容部分的布局范围。这个问题在手机浏览器上看时会更加明显，一些原本在 PC 上正常的图片，手机上看也会显示不完全（超出范围）。

**产生环境**

- 设备：手机  电脑
- 浏览器及版本：Firefox 59  Chrome
- 演示地址：无

**复现步奏**

1. 上传图片并打开编辑框
2. 为图片添加说明

**Comment by Vtrois** [comment]
![Ckiw34.png](https://s1.ax1x.com/2018/04/11/Ckiw34.png)
这个问题修复了，在试一下吧
