### ISSUE TITLE
在手机端下载文件有问题

### ISSUE THREAD

**Issue by yb0554** [Vtrois/Dobby#13]
**网站文件在手机端文件无法直接下载**

（需要点击在新标签页打开才能现在，电脑端无此问题，）

**产生环境**

- 设备：（Android手机）
- 浏览器及版本：Chrome
- 演示地址：https://huazhoufan.cn/2018/04/21/wjjjdkznzb/

注：我手机浏览器只有夸克和Chrome，夸克无此现象

**Comment by Vtrois** [comment]
没有复现这个问题
