### ISSUE TITLE
做了个简单的测试发现了几个问题。

### ISSUE THREAD

**Issue by jtnetcc** [Vtrois/Dobby#2]
1.导航二级菜单显示错位。
2.404页面显示为：No input file specified.
3.独立页面不显示链接，直接域名+.html格式结束。
4.主题设置登录页面显示不正常。
5.暂时没有了，手机版本没测试。

**Comment by Vtrois** [comment]
234是一个问题

**Comment by Vtrois** [comment]
1. 与 #1 的问题相同
2. 检查一下你的伪静态文件配置是否正确
3. 这里需要前提是 设置>固定链接 里面配置类似 `/%post_id%.html` 的自定义结构的链接
4. 登录页面配置上如果不填写链接，将默认指向默认登录地址
