### ISSUE TITLE
几个小小的建议

### ISSUE THREAD

**Issue by FHZDCJ** [Vtrois/Dobby#3]
从krotas主题转过来了，但是有些小小的问题

1.Title和云盘标签不可用了，直接显示出文字来了
2.dangerbox这一类的提示框都不可用了
3.页面加了密码以后会变成原本的样子，很普通的一个输入框和按钮
4.右侧的小工具栏目希望能添加自定义的文本内容

作者辛苦了！！！

**Comment by Vtrois** [comment]
兼容在做

**Comment by Vtrois** [comment]
1、云盘标签的话，云盘和本地下载现在使用统一的本地下载，title 已经做了兼容了（#c），Dobby 的文章内容不适合 Kratos 的标题样式。
```
[download title="本地下载"][/download]
```
2、dangerbox标签确实是去掉了，在 Ravenclaw 之前就已经去掉了，这个标签大家反应没什么作用。
3、私密文章的话在博客中不准备做样式，建议用插件实现，主题只是做单纯的文章展示。
4、小工具已经添加了自定义 HTML 标签的选项。
