### ISSUE TITLE
sc方糖提醒无法使用

### ISSUE THREAD

**Issue by SaledCabbage** [Vtrois/Dobby#7]
加入sc方糖微信提醒的代码发现只能收到邮件信息，方糖推送提醒无法使用。代码放在其他主题上可以使用

**Comment by Vtrois** [comment]
这里的提醒是文章被回复的提醒吗？

**Comment by Vtrois** [comment]
新增了功能：主题设置->文章配置->微信推送，填入 SCKEY 即可实现方糖评论微信推送功能。

**Comment by Vtrois** [comment]
@zhtw2013 这里新增了几条翻译，辛苦增加一下。

**Comment by SaledCabbage** [comment]
我修改的时候感觉在邮件推送同时微信可以同时达到一样的效果，我建议加入TalkAdmin功能，实现效果应该是一样的。我加入下代码试一下，可以的话我给你po上来。

**Comment by Vtrois** [comment]
@SaledCabbage 邮件推送的话感觉就没有太大必要，WordPress 默认是有邮件提醒的，不过可以加一个功能，代码格式请按照例子书写。

**Comment by SaledCabbage** [comment]
测试过了。你网站上的源码还是用不了。这里的可以。现在又事情，回头把代码发给你加一下吧。

**Comment by Vtrois** [comment]
我这里测试是正常的，你那边如果有问题的话，抓包数据发一下看看。

**Comment by SaledCabbage** [comment]
这是修改了的comment.php片段。需要在Server酱中加入一条下行命令
`/**
 * Add the reply WeChat push
 *
 * @author Vtrois <seaton@vtrois.com>
 * @license GPL-3.0
 * @since 1.0
 */
if (dobby_option('single_comment_sc')) {
    add_action('comment_post', 'sc_send', 19, 2);
    function sc_send($comment_id) {
        $comment = get_comment($comment_id);
		$desp = "**".$comment->comment_author."** 在你的站点中说到：\n\n".$comment->comment_content; 
        $key = dobby_option('single_comment_key');
        $postdata = http_build_query(  
            array(  
				'TA_action_on' => '1',
				'TA_title' => __('You have a new review','dobby'),
				'TA_content' => $desp,
				'TA_post_id' => $comment->comment_post_ID,
				'TA_comment_id' => $comment_id
            )
        );
        $opts = array('http' =>  
            array(
            'method'  => 'POST',  
            'header'  => 'Content-type: application/x-www-form-urlencoded',  
            'content' => $postdata  
            )  
        );
        $context = stream_context_create($opts);
		return $result = file_get_contents('http://sc.ftqq.com/webhook/'.$key, false, $context);
    }
}
`
Server酱中命令模板如下：
`<p>请选择需要的操作：</p><a href="http://你的域名/wp-admin/comment.php?c={{$TA_comment_id}}&action=approve#wpbdoy-content" class="btn btn-warning font-white">批准</a>&nbsp;<a href="http://你的域名/wp-admin/comment.php?c={{$TA_comment_id}}&action=trash#wpbdoy-content" class="btn btn-warning font-white">回收站</a>&nbsp;<a href="http://你的域名/wp-admin/comment.php?c={{$TA_comment_id}}&action=spam#wpbdoy-content" class="btn btn-warning font-white">垃圾评论</a>&nbsp;<a href="http://你的域名/?p={{$TA_post_id}}&replytocom={{$TA_comment_id}}#respond" class="btn btn-primary font-white">回复评论</a>`

**Comment by Vtrois** [comment]
好的，我看一下这个问题

**Comment by SaledCabbage** [comment]
刚才发送的可以使用。只是提醒的形式不同，提供了选项。提供个参考，可以让用户选择。

**Comment by Vtrois** [comment]
保留这个功能，上面的代码可以深度DIY推送功能，需要自己动手操作修改即可。
